name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript check
        run: npm run typecheck

      - name: Run tests
        run: npm test

  build-docker-images:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build client image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./client/Dockerfile
          tags: financeapp-client:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build server image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./server/Dockerfile
          tags: financeapp-server:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max
