name: CI Pipeline

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Clean install dependencies in server
        run: |
          cd server
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install

      - name: Run tests
        run: |
          cd server
          npm test

  build-docker-images:
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build client image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./client/Dockerfile
          tags: financeapp-client:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build server image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./server/Dockerfile
          tags: financeapp-server:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max
